Implement all transactions logic
thnamm/ftw-daily-test pull request #1
Opened 2020-11-03 04:14 UTC by thnamm

2020-11-03 07:22 UTC, rush1506 requested changes

2020-11-03 07:22 UTC, rush1506 commented on ext/transaction-process/process.edn
> +   [{:name :action/create-booking
Should use Flex's new create-pending-booking-action

2020-11-03 07:22 UTC, rush1506 commented on server/api-util/helper.js
> +  if (queryResult.data.data.length === 0) return true;
What do you think about extracting the data out instead of accessing nested data for so much time?

2020-11-03 07:22 UTC, rush1506 commented on server/api-util/helper.js
> +        || item.attributes.lastTransition === TRANSITION_DECLINE_AFTER_EXPIRE
Accessing continuous attributes like this this should be avoided, should leave out lastTransition instead of coding long lines for accessing the object

2020-11-03 07:22 UTC, rush1506 commented on server/api-util/sdk.js
> +exports.getIntergrationSdk = (req, res) => {
What is req and res used for?

2020-11-03 07:22 UTC, rush1506 commented on server/api-util/helper.js
> +exports.checkIsFirstTimeOfCustomer = (queryResult) => {
you can just name this `isFirstTimeCustomer` or `isFirstPurchase`

2020-11-03 07:22 UTC, rush1506 commented on server/api/initiate-privileged.js
> +      // Calculate fist time of customer booking
We don't need this comment, your code should already express what you are trying to do. Only write comment when you are doing complicated logic.

2020-11-03 07:22 UTC, rush1506 commented on server/api/transition-privileged.js
> +        units: restParams.units,
Why don't you just take units and seats out above?

2020-11-03 07:22 UTC, rush1506 commented on server/api/transition-privileged.js
> +      const isFirstTime = checkIsFirstTimeOfCustomer(queryResult);
This code is duplicated

2020-11-03 07:22 UTC, rush1506 commented on src/components/BookingBreakdown/BookingBreakdown.js
> +    isTeacherType,
If you add in new props, you need to declare the propTypes for it

2020-11-03 07:22 UTC, rush1506 commented on src/components/BookingBreakdown/BookingBreakdown.js
> +    isTeacherType,
Also get me a better name

2020-11-03 07:22 UTC, rush1506 commented on src/components/BookingBreakdown/LineItemBasePriceMaybe.js
> +  const { transaction, unitType, intl, isTeacherType } = props;
Need to add propTypes

2020-11-03 07:22 UTC, rush1506 commented on src/components/BookingBreakdown/LineItemBookingPeriod.js
> +  const endDay = isUnit || isNightly ? localEndDateRaw : moment(localEndDateRaw).subtract(1, 'days');
Do you really need to subtract endDay by 1 day?

2020-11-03 07:22 UTC, rush1506 commented on src/components/BookingBreakdown/LineItemBookingPeriod.js
> +// import { dateFromAPIToLocalNoon } from '../../util/dates';
Remove don't need to comment here

2020-11-03 07:22 UTC, rush1506 commented on src/components/BookingPanel/BookingPanel.js
> +    currentUser,
propTypes for new props

2020-11-03 07:22 UTC, rush1506 commented on src/components/BookingTimeInfo/BookingTimeInfo.js
> +        .subtract(1, 'days')
Do you really need to subtract by 1 day

2020-11-03 07:22 UTC, rush1506 commented on src/components/TransactionPanel/BreakdownMaybe.js
> +  const isTeacherType = transaction && transaction.listing && transaction.listing.attributes && transaction.listing.attributes.publicData && transaction.listing.attributes.publicData.isTeacherType;
Did you forget our coding convention?

2020-11-03 07:22 UTC, rush1506 commented on src/components/TransactionPanel/CancelActionButtonAfterAcceptedMaybe.js
> +    className,
What is the propTypes for all of these props

2020-11-03 07:22 UTC, rush1506 commented on src/components/TransactionPanel/CancelActionButtonsMaybe.js
> +export default CancelActionButtonsMaybe;
This files seem like a copy from `CancelActionButtonAfterAcceptedMaybe.js` why didn't you make a master component for these?

2020-11-03 07:22 UTC, rush1506 commented on src/components/TransactionPanel/CancelActionButtonsMaybe.js
> +    cancelInProgress,
propTypes needed

2020-11-03 07:22 UTC, rush1506 commented on src/containers/CheckoutPage/CheckoutPage.js
> +      ? minutesBetween(existingTransaction.attributes.lastTransitionedAt, new Date()) >= 15
Should make 15 into a configuration, at this point we can't figure what 15 is for

2020-11-03 07:22 UTC, rush1506 commented on src/containers/CheckoutPage/CheckoutPage.js
> +      pageData.bookingDates.bookingDisplayStart &&
You did not implement sessionHelper for saving booking display start/end time

2020-11-03 07:22 UTC, rush1506 commented on src/containers/TransactionPage/TransactionPage.duck.js
> +  const transType = currentTransactions.data.data.attributes.lastTransition === TRANSITION_EXPIRE_FULL_REFUND_PERIOD
Do you really need to check it here? Because you can make use of the `nextTransition` data

2020-11-03 07:22 UTC, rush1506 commented on src/containers/TransactionPage/TransactionPage.duck.js
> +  const transType = currentTransactions.data.data.attributes.lastTransition === TRANSITION_EXPIRE_FULL_REFUND_PERIOD
You can use `nextTransition` data instead of last transition

2020-11-03 07:22 UTC, rush1506 commented on src/containers/TransactionPage/TransactionPage.duck.js
> +  const transType = currentTransactions.data.data.attributes.lastTransition === TRANSITION_EXPIRE_FULL_REFUND_PERIOD
You can use `nextTransition data instead of last transition

2020-11-03 07:22 UTC, rush1506 commented on src/containers/TransactionPage/TransactionPage.duck.js
> +
`cancelSaleAfterAcceptedByProvider`, `cancelSaleAfterAcceptedByCustomer`, `cancelSale `,... look similar in terms of logic can you generalise it a bit?

2020-11-03 07:22 UTC, rush1506 commented on src/ducks/user.duck.js
> +export const fetchExpireCurrentUserNotifications = () => (dispatch, getState, sdk) => {
This would conflict with `fetchCurrentUserNotifications `, they can override each other.

2020-11-03 07:22 UTC, rush1506 commented on src/forms/BookingDatesForm/BookingDatesForm.js
> +      ? new Date(new Date(e.bookingDates.date).setHours(Number.parseInt(e.bookingStartTime)))
use moment in dates.js

2020-11-03 07:22 UTC, rush1506 commented on src/forms/BookingDatesForm/BookingDatesForm.js
> +    const endDate = e.bookingDates && e.bookingStartTime
use moment in dates.js

2020-11-03 07:22 UTC, rush1506 commented on src/forms/BookingDatesForm/BookingDatesForm.js
> +      ? new Date(new Date(new Date(e.bookingDates.date).setDate(new Date(e.bookingDates.date).getDate() + 1)).setHours(Number.parseInt(e.bookingStartTime) + this.props.units))
use moment in dates.js

2020-11-03 07:22 UTC, rush1506 commented on src/forms/BookingDatesForm/BookingDatesForm.js
> +      ? new Date(new Date(e.bookingDates.date).setHours(Number.parseInt(e.bookingStartTime)))
use moment in dates.js

2020-11-03 07:22 UTC, rush1506 commented on src/forms/BookingDatesForm/BookingDatesForm.js
> +      ? new Date(new Date(e.bookingDates.date).setHours(Number.parseInt(e.bookingStartTime) + this.props.units))
use moment in dates.js

2020-11-03 07:22 UTC, rush1506 commented on src/forms/BookingDatesForm/BookingDatesForm.js
> +      ? new Date(new Date(date).setHours(Number.parseInt(time)))
use moment in dates.js

2020-11-03 07:22 UTC, rush1506 commented on src/forms/BookingDatesForm/BookingDatesForm.js
> +      ? new Date(new Date(new Date(date).setDate(new Date(date).getDate() + 1)).setHours(Number.parseInt(time) + units))
use moment in dates.js

2020-11-03 07:22 UTC, rush1506 commented on src/forms/BookingDatesForm/BookingDatesForm.js
> +            ? new Date(new Date(values.bookingDates.date).setHours(Number.parseInt(values.bookingStartTime)))
use moment in dates.js

2020-11-03 07:22 UTC, rush1506 commented on src/forms/BookingDatesForm/BookingDatesForm.js
> +            ? new Date(new Date(new Date(values.bookingDates.date).setDate(new Date(values.bookingDates.date).getDate() + 1)).setHours(Number.parseInt(values.bookingStartTime) + units))
use moment in dates.js

2020-11-03 07:22 UTC, rush1506 commented on src/forms/BookingDatesForm/BookingDatesForm.js
> +            ? new Date(new Date(values.bookingDates.date).setHours(Number.parseInt(values.bookingStartTime)))
use moment in dates.js

2020-11-03 07:22 UTC, rush1506 commented on src/forms/BookingDatesForm/BookingDatesForm.js
> +            ? new Date(new Date(values.bookingDates.date).setHours(Number.parseInt(values.bookingStartTime) + units))
use moment in dates.js

2020-11-03 07:22 UTC, rush1506 commented on src/forms/BookingDatesForm/BookingTimes.js
> +  '07:00',
Doesn't Flex has code for all of these already?

2020-11-03 07:22 UTC, rush1506 commented on src/forms/BookingDatesForm/EstimatedBreakdownMaybe.js
> +  // const serverDayStart = dateFromLocalToAPI(
Just delete the code no need to comment

2020-11-03 07:22 UTC, rush1506 commented on src/forms/BookingDatesForm/EstimatedBreakdownMaybe.js
> +const estimatedTransaction = (bookingStart, bookingEnd, bookingDisplayStart, bookingDisplayEnd, lineItems, units, seats, userRole) => {
Too many arguments, lets try to reduce it

2020-11-03 07:27 UTC, thnamm commented on server/api-util/sdk.js
> +exports.getIntergrationSdk = (req, res) => {
What is tokenStore in getSdk?

2020-11-04 03:55 UTC, thnamm commented on server/api-util/sdk.js
> +exports.getIntergrationSdk = (req, res) => {
1. req and res in this situation are redundant
2. tokenStore in getSdk is a module that store user's session information

2020-11-12 02:46 UTC, merged